openapi: 3.0.3
info:
  version: 1.0.0-SNAPSHOT
  title: Catlean Monolithic Frontend API
servers:
  - url: http://localhost:9999
    description: Local
  - url: https://api-staging.catlean.fr
    description: Staging

paths:
  /api/v1/me:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - User
      summary: Get Current Logged In User
      operationId: getCurrentUser
      description: |
        Get Current Logged In User
      responses:
        "200":
          description: 'Successfully current user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentUserResponseContract'
              example:
                user:
                  id: 16
                  email: john.doe@catlean.fr
                  organization:
                    id: 42
                    name: Catlean
                errors:
                  { }
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /api/v1/pull-request/histogram:
    get:
      security:
        - bearerAuth: []
      tags:
        - PullRequest
      summary: Get PullRequest Histogram
      operationId: getPullRequestHistogram
      description: |
        Get PullRequest Histogram
      parameters:
        - in: query
          name: organization_name
          schema:
            type: string
            example: armis
        - in: query
          name: team_name
          schema:
            type: string
            example: data-team
        - in: query
          name: histogram_type
          schema:
            type: string
            example: size-limit
      responses:
        "200":
          description: 'Successfully retrieved pull request histogram'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistogramResponseContract'
              example:
                data:
                  - start_date_range: 12/08/1992
                    data_above_limit: 11
                    data_below_limit: 22
                  - start_date_range: 24/09/1992
                    data_above_limit: 1
                    data_below_limit: 10
                errors:
                  {}
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "404":
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatleanErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
  schemas:
    CatleanErrorsContract:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
    CatleanErrorContract:
      type: object
      required:
        - code
        - message
        - metadata
      properties:
        code:
          type: string
          example: F.NOT_FOUND
        message:
          type: string
          example: Histogram not found
        metadata:
          type: object
    HistogramDataResponseContract:
      required:
        - start_date_range
        - data_above_limit
        - data_below_limit
      properties:
        start_date_range:
          type: string
          example: 12/08/1992
        data_above_limit:
          type: integer
          example: 95
        data_below_limit:
          type: integer
          example: 111
    HistogramResponseContract:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/HistogramDataResponseContract'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
    OrganizationContract:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          example: 16
        name:
          type: string
          example: Catlean
    UserContract:
      type: object
      required:
        - id
        - email
        - organization
      properties:
        id:
          type: integer
          example: 16
        email:
          type: string
          example: john.doe@catlean.fr
        organization:
          type: object
          items:
            $ref: '#/components/schemas/OrganizationContract'
    CurrentUserResponseContract:
      type: object
      required:
        - user
        - organization
      properties:
        user:
          type: object
          items:
            $ref: '#/components/schemas/UserContract'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/CatleanErrorContract'
