openapi: 3.0.3
info:
  version: 1.0.0-SNAPSHOT
  title: Catlean Monolithic Frontend API
servers:
  - url: http://localhost:9999
    description: Local


paths:
  /api/v1/pull-request/histogram:
    get:
      tags:
        - PullRequest
      summary: Get PullRequest Histogram
      operationId: getPullRequestHistogram
      description: |
        Get PullRequest Histogram
      responses:
        200:
          description: Job ran successfully
        400:
          description: A functional error has occurred
        500:
          description: An internal error has occurred
