databaseChangeLog:
  - changeSet:
      id: 00000000_init_schema_with_pr
      author: poucif
      changes:
        - createSequence:
            sequenceName: pull_request


        - createTable:
            tableName: pull_request
            columns:
              - column:
                  name: pk
                  type: BIGINT
                  constraints:
                    primaryKey: true
                    primaryKeyName: pull_request_pk
                    nullable: false
              - column:
                  name: number
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: commit_number
                  type: BIGINT
              - column:
                  name: deleted_line_number
                  type: BIGINT
              - column:
                  name: added_line_number
                  type: BIGINT
              - column:
                  name: creation_date
                  type: timestamp(6)
                  constraints:
                    nullable: false
              - column:
                  name: last_update_date
                  type: timestamp(6)
                  constraints:
                    nullable: false
              - column:
                  name: merge_date
                  type: timestamp(6)
              - column:
                  name: is_merged
                  type: BOOLEAN
                  defaultValueBoolean: false
              - column:
                  name: is_draft
                  type: BOOLEAN
                  defaultValueBoolean: false
              - column:
                  name: state
                  type: VARCHAR(200)
              - column:
                  name: vcs_url
                  type: VARCHAR(200)
              - column:
                  name: title
                  type: VARCHAR(300)
              - column:
                  name: author_login
                  type: VARCHAR(200)
              - column:
                  name: technical_creation_date
                  type: timestamp(6)
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
              - column:
                  name: technical_modification_date
                  type: timestamp(6)
                  constraints:
                    nullable: false
                  defaultValueComputed: CURRENT_TIMESTAMP
