json-local-storage:
  root-directory: /tmp/json_local_storage

github:
  app:
    api: "https://api.github.com/"
    url-host: "https://github.com/"
    size: 100
    github-app-id: ${GITHUB_APP_ID}
    private-key-certificate-path: ${GITHUB_PRIVATE_KEY_PATH}
  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}

auth0:
  api-audience: ${AUTH0_AUDIENCE}
  api-issuer: ${AUTH0_ISSUER}

aws:
  raw-bucket-name: ${S3_DATALAKE_BUCKET_NAME}

web:
  cors:
    hosts: ${FRONTEND_CORS_HOST}

spring:
  application:
    name: symeo-monolithic-backend
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://postgres_exposition_host:5432/symeo-monolithic-backend?rewriteBatchedStatements=true
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 10000
      idleTimeout: 30000
      maxLifetime: 60000
      maximumPoolSize: 10
      initial-size: 1
      minimumIdle: 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
        event:
          merge:
            entity_copy_observer: allow
        format_sql: false
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          time_zone: Europe/Paris
          batch_size: 10000
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: false
    open-in-view: false
    show-sql: false

server:
  port: 9999

