version: '3'

services:
  exposition-database:
    platform: linux/arm64/v8
    image: "postgres:13"
    container_name: "exposition-database"
    hostname: postgres_exposition_host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=symeo-monolithic-backend
      - AUTH0_AUDIENCE=https://api-staging.symeo.io
      - AUTH0_ISSUER=https://symeo-staging.eu.auth0.com/
    ports:
      - "5432:5432"
    networks:
      - symeo-backend-network

  symeo-monolithic-backend:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    networks:
      - symeo-backend-network

networks:
  symeo-backend-network:
    driver: bridge
