@startuml
'https://plantuml.com/sequence-diagram
participant cronjob order 10
participant "symeo-monolithic-backend" as backend order 20
participant github order 30
database "raw-storage" order 40
database "exposition-storage" order 50
collections "google-sheet" order 60
actor User order 70



alt collect data
cronjob -> backend : trigger data collection
cronjob <-- backend
"symeo-processor" -> github: get all repositories
"symeo-processor" <-- github
"symeo-processor" -> "raw-storage": save repositories
"symeo-processor" <-- "raw-storage"
"symeo-processor" -> github: get all pull requests for repository
"symeo-processor" <-- github
"symeo-processor" -> github: get pull request details
"symeo-processor" <-- github
"symeo-processor" -> "raw-storage": save pull requests
"symeo-processor" <-- "raw-storage"
end

alt aggregate data
"symeo-processor" -> "raw-storage": read pull requests
"symeo-processor" <-- "raw-storage": pull requests
"symeo-processor" -> "symeo-processor": compute pull requests insights
"symeo-processor" -> "exposition-storage": save pull requests insights
end

alt expose data
User -> "google-sheet": read insights
"google-sheet" -> "exposition-storage": read insights
end

@enduml