version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package -T 4
      - run:
          name: Test
          command: mvn test -T 4

workflows:
  build-test:
    jobs:
      - build-and-test
