openapi: 3.0.3
info:
  version: 1.0.0-SNAPSHOT
  title: Symeo Monolithic Backend API
servers:
  - url: http://localhost:9999
    description: Local


paths:
  /job/v1/data-processing/organization/repositories:
    post:
      tags:
        - DataProcessingJob
      summary: Start to collect and process data for organizationId and repositoryIds
      operationId: startDataProcessingJobForOrganizationIdAndRepositoryIds
      description: |
        Start to collect and process data given an organizationId and repositoryIds
      parameters:
        - in: header
          name: X-SYMEO-JOB-KEY-X
          required: true
          schema:
            type: string
      requestBody:
        description: organizationId and repositoryIds
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostStartDataProcessingJobForOrganizationContract'
      responses:
        "200":
          description: 'Job started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /job/v1/data-processing/organization/vcs_organization:
    post:
      tags:
        - DataProcessingJob
      summary: Start to collect and process data for organizationId and vcsOrganizationId
      operationId: startDataProcessingJobForOrganizationIdAndVcsOrganizationId
      description: |
        Start to collect and process data given an organizationId and vcsOrganizationId
      parameters:
        - in: header
          name: X-SYMEO-JOB-KEY-X
          required: true
          schema:
            type: string
      requestBody:
        description: organizationId and vcsOrganizationId
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostStartDataProcessingJobForVcsOrganizationContract'
      responses:
        "200":
          description: 'Job started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /job/v1/data-processing/organization/team/repositories:
    post:
      tags:
        - DataProcessingJob
      summary: Start to collect and process data for organizationId and teamId and repositoryIds
      operationId: startDataProcessingJobForOrganizationIdAndTeamIdAndRepositoryIds
      description: |
        Start to collect and process data given an organizationId and teamId and repositoryIds
      parameters:
        - in: header
          name: X-SYMEO-JOB-KEY-X
          required: true
          schema:
            type: string
      requestBody:
        description: organizationId and teamId and repositoryIds
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostStartDataProcessingJobForTeamContract'
      responses:
        "200":
          description: 'Job started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /job/v1/data-processing/all:
    get:
      tags:
        - DataProcessingJob
      summary: Start data collection jobs for all teams of all organizations
      operationId: startAllDataCollectionJobs
      description: |
        Start to collect and process data from clients' platforms
      parameters:
        - in: header
          name: X-SYMEO-JOB-KEY-X
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'All jobs started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /sh/v1/testing:
    post:
      security:
        - apiKeyAuth: [ ]
      tags:
        - Testing
      summary: Collect testing data from ci script
      operationId: collectTestingData
      description: |
        Collect testing data from ci script
      parameters:
        - in: header
          name: X-API-KEY
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectTestingDataRequestContract'
      responses:
        "200":
          description: 'Successfully collected testing data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "500":
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  responses:
    UnauthorizedError:
      description: Api key is missing or invalid
  schemas:
    DataProcessingSymeoErrorsContract:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/DataProcessingSymeoErrorContract'
    DataProcessingSymeoErrorContract:
      type: object
      required:
        - code
        - message
        - metadata
      properties:
        code:
          type: string
          example: F.NOT_FOUND
        message:
          type: string
          example: Jobs not found
        metadata:
          type: object
    PostStartDataProcessingJobForOrganizationContract:
      type: object
      required:
        - organization_id
        - repository_ids
      properties:
        organization_id:
          type: string
          format: uuid
        repository_ids:
          type: array
          items:
            type: string
    PostStartDataProcessingJobForTeamContract:
      type: object
      required:
        - organization_id
        - repository_ids
        - team_id
      properties:
        organization_id:
          type: string
          format: uuid
        team_id:
          type: string
          format: uuid
        repository_ids:
          type: array
          items:
            type: string
    PostStartDataProcessingJobForVcsOrganizationContract:
      type: object
      required:
        - organization_id
        - vcs_organization_id
      properties:
        organization_id:
          type: string
          format: uuid
        vcs_organization_id:
          type: integer
          format: int64
    CollectTestingDataRequestContract:
      type: object
      properties:
        coverage_report:
          type: string
        coverage_report_type:
          type: string
        code_line_count:
          type: integer
        test_line_count:
          type: integer
        test_count:
          type: integer
        test_framework:
          type: string
        test_type:
          type: string
        repository_name:
          type: string
        branch_name:
          type: string
        commit_sha:
          type: string
