openapi: 3.0.3
info:
  version: 1.0.0-SNAPSHOT
  title: Symeo Monolithic Backend API
servers:
  - url: http://localhost:9999
    description: Local


paths:
  /job/v1/data-processing/organization:
    get:
      tags:
        - DataProcessingJob
      summary: Start to collect and process data for an organization
      operationId: startDataProcessingJobForOrganizationId
      description: |
        Start to collect and process data given an organization id
      parameters:
        - in: query
          name: organization_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 'Job started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /job/v1/data-processing/team:
    get:
      tags:
        - DataProcessingJob
      summary: Start to collect and process data for a team
      operationId: startDataProcessingJobForOrganizationIdAndTeamId
      description: |
        Start to collect and process data given an organization id and a team id
      parameters:
        - in: query
          name: organization_id
          required: true
          schema:
            type: string
            format: uuid
        - in: query
          name: team_id
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: 'Job started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"
  /job/v1/data-processing/all:
    get:
      tags:
        - DataProcessingJob
      summary: Start data collection jobs for all teams of all organizations
      operationId: startAllDataCollectionJobs
      description: |
        Start to collect and process data from clients' platforms
      parameters:
        - in: header
          name: X-SYMEO-JOB-KEY-X
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'All jobs started successfully'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  [ ]
        404:
          description: Not found error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
        500:
          description: An internal error has occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataProcessingSymeoErrorsContract'
              example:
                errors:
                  - code: "T.POSTGRES_TIMEOUT"
                    message: "Failed to open connection with database"


components:
  schemas:
    DataProcessingSymeoErrorsContract:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/DataProcessingSymeoErrorContract'
    DataProcessingSymeoErrorContract:
      type: object
      required:
        - code
        - message
        - metadata
      properties:
        code:
          type: string
          example: F.NOT_FOUND
        message:
          type: string
          example: Jobs not found
        metadata:
          type: object