databaseChangeLog:
  - include:
      file: db/changelog/changelogs/00000000_init_organization_storage_schema.sql
  - include:
      file: db/changelog/changelogs/00000010_init_exposition_storage_schema.sql
  - include:
      file: db/changelog/changelogs/00000020_init_job_storage_schema.sql
  - include:
      file: db/changelog/changelogs/00000030_update_varchar_size.sql
  - include:
      file: db/changelog/changelogs/00000040_add_vcs_url_column_to_tag_table.sql
  - include:
      file: db/changelog/changelogs/00000050_add_commit_testing_data.sql







