Description: Datadog log forwarders
Parameters:
  CloudwatchLogsGroup:
    Type: String
  DatadogForwarderArn:
    Type: String
Resources:
  CatleanBackendApiLogForwarderFilter:
    Type: "AWS::Logs::SubscriptionFilter"
    Properties:
      DestinationArn: !Ref DatadogForwarderArn
      LogGroupName: !Ref CloudwatchLogsGroup
      FilterPattern: ""
      RoleArn: arn:aws:iam::821145449657:role/DatadogIntegrationRole