Description: Datadog log forwarders
Parameters:
  CloudwatchLogsGroup:
    Type: String
  DatadogForwarderArn:
    Type: String
Resources:
  SymeoBackendApiLogForwarderFilter:
    Type: "AWS::Logs::SubscriptionFilter"
    Properties:
      DestinationArn: !Ref DatadogForwarderArn
      LogGroupName: !Ref CloudwatchLogsGroup
      FilterPattern: ""