Description: Symeo Backend - ECR Repositories

Parameters:
  SymeoBackendRepositoryName:
    Type: String
    Default: symeo/backend
  Env:
    Type: String
    Default: staging

Resources:
  SymeoBackendRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub ${SymeoBackendRepositoryName}-${Env}

Outputs:
  SymeoBackendRepository:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${SymeoBackendRepositoryName}-${Env}
  SymeoBackendRepositoryName:
    Value: !Sub ${SymeoBackendRepositoryName}-${Env}
