Description: Catlean Backend - ECS Services

Parameters:
  DesiredCount:
    Type: Number
    Default: 2

  MaxCount:
    Type: Number
    Default: 3

  ECSCluster:
    Type: String

  Tag:
    Type: String

  Env:
    Type: String

  DatalakeS3Bucket:
    Type: String

  DBUsername:
    Type: String

  DBPassword:
    Type: String

  DBUrl:
    Type: String

  ECSTaskRole:
    Type: String

  ECSAutoScaleRole:
    Type: String

  DockerRepository:
    Type: String

  ECSServiceRole:
    Type: String

  CloudwatchLogsGroup:
    Type: String

  TargetGroup:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: bridge
      Family: !Sub CatleanBackend-TaskFamily-${Env}
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/${ECSTaskRole}
      ContainerDefinitions:
      - Name: !Sub CatleanBackendContainer-${Env}
        Image: !Sub ${DockerRepository}:${Tag}
        Essential: true
        MemoryReservation: 1536
        Cpu: 768
        PortMappings:
        - ContainerPort: 9999
          HostPort: 0
          Protocol: tcp
        Environment:
        - Name: NODE_ENV
          Value: !Ref Env
        - Name: AWS_REGION
          Value: !Ref AWS::Region
        - Name: S3_DATALAKE_BUCKET_NAME
          Value: !Ref DatalakeS3Bucket
        - Name: DATABASE_USERNAME
          Value: !Ref DBUsername
        - Name: DATABASE_PASSWORD
          Value: !Ref DBPassword
        - Name: DATABASE_URL
          Value: !Ref DBUrl
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref CloudwatchLogsGroup
            awslogs-region: !Sub ${AWS::Region}
            awslogs-stream-prefix: catlean-backendAssiociatePublicIp

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      ServiceName: !Sub CatleanBackend-Service-${Env}
      Role: !Ref ECSServiceRole
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      LoadBalancers:
      - ContainerName: !Sub CatleanBackendContainer-${Env}
        ContainerPort: 9999
        TargetGroupArn: !Ref TargetGroup

  scalingPolicyUp:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ScalingPolicyUp-${Env}
      PolicyType: StepScaling
      ScalingTargetId: !Ref scalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 30
        MetricAggregationType: Average
        StepAdjustments:
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: 2

  scalingPolicyDown:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub ScalingPolicyDown-${Env}
      PolicyType: StepScaling
      ScalingTargetId: !Ref scalableTarget
      StepScalingPolicyConfiguration:
        AdjustmentType: ChangeInCapacity
        Cooldown: 30
        MetricAggregationType: Average
        StepAdjustments:
        - MetricIntervalUpperBound: 0
          ScalingAdjustment: -1

  scalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxCount
      MinCapacity: !Ref DesiredCount
      ResourceId: !Join [ "/", [ "service", !Ref ECSCluster, !GetAtt ECSService.Name ] ]
      RoleARN: !Sub arn:aws:iam::${AWS::AccountId}:role/${ECSAutoScaleRole}
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ServiceCPUAlarmScaleUp:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: 3
      Statistic: Average
      AlarmName: !Sub CatleanBackendServicescalingCPUscaleUpAlarm-${Env}
      Threshold: 50
      AlarmDescription: Alarm if CPU is too high
      Period: 60
      AlarmActions:
      - !Ref scalingPolicyUp
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value: !Ref ECSCluster
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization

  ServiceCPUAlarmScaleDown:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: 4
      Statistic: Average
      AlarmName: !Sub CatleanBackendServicescalingCPUscaleDownAlarm-${Env}
      Threshold: 10
      AlarmDescription: Alarm if CPU is too low
      Period: 60
      AlarmActions:
      - !Ref scalingPolicyDown
      Namespace: AWS/ECS
      Dimensions:
      - Name: ClusterName
        Value: !Ref ECSCluster
      ComparisonOperator: LessThanThreshold
      MetricName: CPUUtilization

Outputs:
  ServiceName:
    Value: !GetAtt ECSService.Name
  FamilyName:
    Value: !Sub CatleanBackend-TaskFamily-${Env}
