AWSTemplateFormatVersion: '2010-09-09'

Description: Catlean Backend - IAM Roles

Parameters:
  Env:
    Type: String
    Default: staging

Resources:
  CatleanBackendEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub catlean-backend-ec2-role-${Env}
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: "Allow"
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role

  CatleanBackendEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub catlean-backend-ec2-instance-profile-${Env}
      Path: /
      Roles:
      - !Ref CatleanBackendEC2Role

  CatleanBackendServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub catlean-backend-service-role-${Env}
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: "Allow"
          Principal:
            Service:
            - "ecs.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  CatleanBackendAutoScaleRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub catlean-backend-autoscale-role-${Env}
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: "Allow"
          Principal:
            Service:
            - "application-autoscaling.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole

  CatleanBackendTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub catlean-backend-task-role-${Env}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        -
          Effect: "Allow"
          Principal:
            Service:
            - "ecs-tasks.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Path: /
      Policies:
      -
        PolicyName: !Sub LogAuthorization-${Env}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          -
            Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: "*"
      -
        PolicyName: !Sub S3Access-${Env}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          -
            Effect: "Allow"
            Action:
            - "s3:*"
            Resource:
            - "*"

Outputs:
  CatleanBackendEC2Role:
    Value: !Ref CatleanBackendEC2Role
  CatleanBackendEC2InstanceProfile:
    Value: !Ref CatleanBackendEC2InstanceProfile
  CatleanBackendServiceRole:
    Value: !Ref CatleanBackendServiceRole
  CatleanBackendAutoScaleRole:
    Value: !Ref CatleanBackendAutoScaleRole
  CatleanBackendTaskRole:
    Value: !Ref CatleanBackendTaskRole
