AWSTemplateFormatVersion: '2010-09-09'

Description: Catlean Backend - Creation of datalake S3 bucket

Parameters:
  BucketName:
    Type: String
    Description: S3 bucket name
    Default: catlean-datalake

  Env:
    Description: The environment name deployed
    Type: String
    Default: staging

Resources:
  DatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${BucketName}-${Env}
      Tags:
      - Key: Project
        Value: CatleanBackend
      - Key: Env
        Value: !Ref Env
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          -
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"

Outputs:
  DatalakeS3Bucket:
    Value: !Ref DatalakeBucket
