AWSTemplateFormatVersion: '2010-09-09'

Description: Catlean Backend - Creation of datalake S3 bucket

Parameters:
  Env:
    Description: The environment name deployed
    Type: String
    Default: staging

Resources:
  DatalakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub catlean-datalake-${Env}
      Tags:
      - Key: Project
        Value: CatleanBackend
      - Key: Env
        Value: !Ref Env
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          -
            AllowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
  EnvFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub catlean-env-files-${Env}
      Tags:
      - Key: Project
        Value: CatleanBackend
      - Key: Env
        Value: !Ref Env
      VersioningConfiguration:
        Status: Enabled

Outputs:
  DatalakeS3Bucket:
    Value: !Ref DatalakeBucket
  EnvFilesS3Bucket:
    Value: !Ref EnvFilesBucket
