AWSTemplateFormatVersion: '2010-09-09'

Description: Symeo Backend - Creation of all SecurityGroups

Parameters:
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id

  Env:
    Description: The environment name deployed
    Type: String
    Default: staging

Resources:
  SymeoBackendSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub symeo-backend-sg-${Env}
      GroupDescription: symeo-backend-sg
      SecurityGroupIngress:
      -
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        SourceSecurityGroupId: !Ref SymeoBackendAlbSg
      -
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: symeo-backend-sg
      VpcId: !Ref VpcId
  SymeoBackendAlbSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub symeo-backend-alb-sg-${Env}
      GroupDescription: symeo-backend-alb-sg
      SecurityGroupIngress:
      -
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      -
        IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIpv6: ::/0
      -
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      -
        IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIpv6: ::/0
      Tags:
      - Key: Name
        Value: symeo-backend-alb-sg
      VpcId: !Ref VpcId
  SymeoBackendDatabaseSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub symeo-backend-db-sg-${Env}
      GroupDescription: symeo-backend-db-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIpv6: ::/0
      VpcId: !Ref VpcId

Outputs:
  SymeoBackendSg:
    Value: !Ref SymeoBackendSg
  SymeoBackendAlbSg:
    Value: !Ref SymeoBackendAlbSg
  SymeoBackendDatabaseSg:
    Value: !Ref SymeoBackendDatabaseSg
